import { Tender } from '../types';

// Demo data for when live APIs are unavailable or for testing
export function generateDemoTenders(): Tender[] {
  const today = new Date().toISOString();
  const yesterday = new Date(Date.now() - 86400000).toISOString();
  const nextMonth = new Date(Date.now() + 30 * 86400000).toISOString();

  return [
    {
      id: 'demo-1',
      title: 'Lieferung und Montage von beleuchteten Rahmensystemen für Bahnhöfe',
      description:
        'Beschaffung von LED-beleuchteten Informationsrahmen für 12 Bahnhöfe im Stadtgebiet. Inklusive Montage und 5 Jahre Wartung. Aluminium-Rahmen mit Hintergrundbeleuchtung, Format A1 und A0.',
      contracting_authority: 'Stadtwerke München GmbH',
      published_date: today,
      deadline: nextMonth,
      estimated_value: 480000,
      currency: 'EUR',
      cpv_codes: ['31520000', '44212000'],
      cpv_descriptions: ['Leuchten und Beleuchtungszubehör', 'Rahmen und Gestelle'],
      region: 'Bayern',
      bundesland: 'Bayern',
      source_platform: 'TED (EU)',
      source_url: 'https://ted.europa.eu/de/notice/demo-1',
      tender_type: 'Offenes Verfahren',
      keywords_matched: ['LED', 'Beleuchtung', 'Rahmen'],
    },
    {
      id: 'demo-2',
      title: 'Außenbeschilderung und Wegeleitsystem Universitätsklinikum',
      description:
        'Planung, Lieferung und Montage eines vollständigen Wegeleitsystems für das Universitätsklinikum Freiburg. Umfasst Außenschilder, beleuchtete Hinweistafeln und digitale Informationsdisplays.',
      contracting_authority: 'Universitätsklinikum Freiburg',
      published_date: today,
      deadline: new Date(Date.now() + 45 * 86400000).toISOString(),
      estimated_value: 320000,
      currency: 'EUR',
      cpv_codes: ['34992000', '31521200'],
      cpv_descriptions: ['Anzeigetafeln, Hinweisschilder', 'Außenleuchten'],
      region: 'Baden-Württemberg',
      bundesland: 'Baden-Württemberg',
      source_platform: 'DTVP - Deutsches Vergabeportal',
      source_url: 'https://www.dtvp.de/notice/demo-2',
      tender_type: 'Offenes Verfahren',
      keywords_matched: ['Beschilderung', 'Schilder', 'Hinweisschild'],
    },
    {
      id: 'demo-3',
      title: 'LED-Straßenbeleuchtung Erneuerung - Los 3: Innenstadt',
      description:
        'Erneuerung der Straßenbeleuchtung im Innenstadtbereich. Lieferung und Installation von LED-Mastleuchten inkl. intelligenter Steuerung. Ca. 450 Lichtpunkte.',
      contracting_authority: 'Stadt Dortmund - Tiefbauamt',
      published_date: today,
      deadline: new Date(Date.now() + 60 * 86400000).toISOString(),
      estimated_value: 1200000,
      currency: 'EUR',
      cpv_codes: ['31527260', '45316110'],
      cpv_descriptions: ['LED-Lampen', 'Installation von Straßenbeleuchtungsanlagen'],
      region: 'Nordrhein-Westfalen',
      bundesland: 'Nordrhein-Westfalen',
      source_platform: 'Vergabe.NRW',
      source_url: 'https://www.vergabe.nrw.de/notice/demo-3',
      tender_type: 'Offenes Verfahren',
      keywords_matched: ['LED', 'Beleuchtung'],
    },
    {
      id: 'demo-4',
      title: 'Lieferung von Schaukästen und beleuchteten Aushangrahmen',
      description:
        'Beschaffung von wettergeschützten Schaukästen (A2-Format) und beleuchteten Aushangrahmen für 45 Standorte im Landkreis. Maße: B x H = 700 x 1000 mm, Tiefe 100 mm.',
      contracting_authority: 'Landkreis Osnabrück',
      published_date: yesterday,
      deadline: new Date(Date.now() + 21 * 86400000).toISOString(),
      estimated_value: 85000,
      currency: 'EUR',
      cpv_codes: ['44212000', '31520000'],
      cpv_descriptions: ['Rahmen und Gestelle', 'Leuchten und Beleuchtungszubehör'],
      region: 'Niedersachsen',
      bundesland: 'Niedersachsen',
      source_platform: 'Bund.de - Öffentliche Aufträge',
      source_url: 'https://www.bund.de/notice/demo-4',
      tender_type: 'Unterschwellenvergabe',
      keywords_matched: ['Schaukasten', 'Leuchtrahmen', 'Rahmen', 'Beleuchtung'],
    },
    {
      id: 'demo-5',
      title: 'Messebau und Ausstellungsrahmen für Tourismusmesse',
      description:
        'Konzeption, Planung und Aufbau eines Messestands inkl. beleuchteter Ausstellungsrahmen, Displaywände und Lichtdecken für die Tourismusmesse Berlin.',
      contracting_authority: 'Landestourismusverband Berlin e.V.',
      published_date: yesterday,
      deadline: new Date(Date.now() + 15 * 86400000).toISOString(),
      estimated_value: 45000,
      currency: 'EUR',
      cpv_codes: ['39154000', '31520000'],
      cpv_descriptions: ['Ausstellungsausstattung', 'Leuchten und Beleuchtungszubehör'],
      region: 'Berlin',
      bundesland: 'Berlin',
      source_platform: 'Vergabemarktplatz Berlin-Brandenburg',
      source_url: 'https://www.vergabemarktplatz.de/notice/demo-5',
      tender_type: 'Verhandlungsverfahren',
      keywords_matched: ['Leuchtrahmen', 'Beleuchtung', 'Display'],
    },
    {
      id: 'demo-6',
      title: 'Hinweisschilder und Beschilderungssystem Naturpark',
      description:
        'Lieferung und Montage von Wanderschildern, Informationstafeln und wetterfesten Rahmensystemen für den Naturpark Rhön. Material: Edelstahl und Aluminium.',
      contracting_authority: 'Biosphärenreservat Rhön',
      published_date: yesterday,
      deadline: new Date(Date.now() + 35 * 86400000).toISOString(),
      estimated_value: 62000,
      currency: 'EUR',
      cpv_codes: ['34992300', '44212000'],
      cpv_descriptions: ['Straßenschilder', 'Rahmen und Gestelle'],
      region: 'Bayern',
      bundesland: 'Bayern',
      source_platform: 'TED (EU)',
      source_url: 'https://ted.europa.eu/de/notice/demo-6',
      tender_type: 'Unterschwellenvergabe',
      keywords_matched: ['Rahmen', 'Beschilderung', 'Schilder'],
    },
    {
      id: 'demo-7',
      title: 'Lichtdecken und LED-Panel für Verwaltungsgebäude',
      description:
        'Modernisierung der Innenbeleuchtung im Verwaltungsgebäude der Kreisverwaltung. Lieferung und Einbau von LED-Panels, Lichtdeckensystemen und Steuerungstechnik. Ca. 2800 m² Nutzfläche.',
      contracting_authority: 'Kreisverwaltung Mainz-Bingen',
      published_date: yesterday,
      deadline: new Date(Date.now() + 42 * 86400000).toISOString(),
      estimated_value: 890000,
      currency: 'EUR',
      cpv_codes: ['31527260', '31524000'],
      cpv_descriptions: ['LED-Lampen', 'Deckenleuchten und Wandleuchten'],
      region: 'Rheinland-Pfalz',
      bundesland: 'Rheinland-Pfalz',
      source_platform: 'HAD - Hessische Ausschreibungsdatenbank',
      source_url: 'https://had.de/notice/demo-7',
      tender_type: 'Offenes Verfahren',
      keywords_matched: ['LED', 'Beleuchtung'],
    },
  ];
}
